import { createStyles } from "antd-style"

export const useStyles = createStyles(({ token }) => ({
	browserContainer: {
		display: "flex",
		flexDirection: "column",
		height: "100%",
		minHeight: 0,
		backgroundColor: token.colorBgContainer,
	},
	chrome: {
		flex: "none",
		border: `1px solid ${token.colorBorderSecondary}`,
		borderBottom: 0,
		borderRadius: `${token.borderRadiusLG}px ${token.borderRadiusLG}px 0 0`,
		overflow: "hidden",
		backgroundColor: token.colorBgLayout,
		userSelect: "none",
	},
	tabBar: {
		display: "flex",
		alignItems: "center",
		gap: token.paddingSM,
		height: 38,
		padding: `0 ${token.paddingSM}px`,
		borderBottom: `1px solid ${token.colorBorderSecondary}`,
		backgroundColor: token.colorBgLayout,
	},
	windowControls: {
		display: "flex",
		alignItems: "center",
		gap: 6,
		padding: "0 4px",
		flex: "none",
		pointerEvents: "none",
		cursor: "default",
		"> span": {
			display: "block",
			width: 8,
			height: 8,
			borderRadius: "50%",
		},
		"> span:nth-child(1)": {
			backgroundColor: token.colorError,
		},
		"> span:nth-child(2)": {
			backgroundColor: token.colorWarning,
		},
		"> span:nth-child(3)": {
			backgroundColor: token.colorSuccess,
		},
	},
	activeTab: {
		display: "flex",
		alignItems: "center",
		gap: 6,
		minWidth: 0,
		maxWidth: "min(360px, 45%)",
		height: 30,
		padding: `0 ${token.paddingSM}px`,
		borderRadius: `${token.borderRadius}px ${token.borderRadius}px 0 0`,
		backgroundColor: token.colorBgContainer,
		color: token.colorText,
		fontSize: token.fontSizeSM,
		pointerEvents: "none",
		cursor: "default",
		"> span:nth-child(2)": {
			overflow: "hidden",
			textOverflow: "ellipsis",
			whiteSpace: "nowrap",
		},
	},
	tabClose: {
		flex: "none",
		fontSize: 16,
		lineHeight: 1,
		color: token.colorTextTertiary,
	},
	tabActions: {
		marginLeft: "auto",
		flex: "none",
		color: token.colorTextSecondary,
		pointerEvents: "none",
		"& [data-testid='detail-header']": {
			width: "auto",
			pointerEvents: "auto",
		},
	},
	nonInteractiveControl: {
		display: "inline-flex",
		pointerEvents: "none",
		cursor: "default",
	},
	toolbar: {
		display: "flex",
		alignItems: "center",
		gap: token.paddingSM,
		height: 46,
		padding: `0 ${token.paddingSM}px`,
		backgroundColor: token.colorBgContainer,
	},
	navigationControls: {
		display: "flex",
		alignItems: "center",
		justifyContent: "center",
		gap: 4,
		height: 28,
		color: token.colorTextTertiary,
		pointerEvents: "none",
		cursor: "default",
	},
	addressBar: {
		display: "flex",
		alignItems: "center",
		gap: 8,
		minWidth: 0,
		flex: 1,
		height: 32,
		padding: `0 ${token.paddingSM}px`,
		borderRadius: token.borderRadiusLG,
		backgroundColor: token.colorFillQuaternary,
		color: token.colorTextSecondary,
		fontSize: token.fontSizeSM,
		pointerEvents: "auto",
		cursor: "text",
		userSelect: "text",
		WebkitUserSelect: "text",
		"> span": {
			overflow: "hidden",
			textOverflow: "ellipsis",
			whiteSpace: "nowrap",
		},
	},
	content: {
		flex: "1 1 auto",
		minHeight: 0,
		overflow: "auto",
		border: `1px solid ${token.colorBorderSecondary}`,
		borderTop: 0,
		backgroundColor: token.colorBgContainer,
	},
	screenshot: {
		display: "block",
		width: "100%",
		height: "auto",
		objectFit: "contain",
		objectPosition: "top center",
	},
	imageError: {
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		justifyContent: "center",
		gap: token.paddingXS,
		minHeight: 220,
		padding: token.paddingLG,
		color: token.colorTextSecondary,
		fontSize: token.fontSizeSM,
		"> div": {
			color: token.colorText,
			fontWeight: 500,
		},
	},
}))
