"""第三方 CLI 持久化服务包。"""

from app.service.cli_manager.models import (
    CliApplyRequest,
    CliApplyResult,
    CliCommandValidation,
    CliConfigDir,
    CliConfigDirData,
    CliInstallStep,
    CliListItem,
    CliListResult,
    CliManagerError,
    CliManagerPaths,
    CliPathLink,
    CliPathLinkData,
    CliRegistryData,
    CliRegistryItem,
    CliRegistryItemData,
    CliRemoveResult,
    CliRestoreIssue,
    CliRestoreResult,
    CliValidationResult,
    CliWritePaths,
    CommandRunResult,
)
from app.service.cli_manager.service import CliManagerService

__all__ = [
    "CliApplyRequest",
    "CliApplyResult",
    "CliCommandValidation",
    "CliConfigDir",
    "CliConfigDirData",
    "CliInstallStep",
    "CliListItem",
    "CliListResult",
    "CliManagerError",
    "CliManagerPaths",
    "CliManagerService",
    "CliPathLink",
    "CliPathLinkData",
    "CliRegistryData",
    "CliRegistryItem",
    "CliRegistryItemData",
    "CliRemoveResult",
    "CliRestoreIssue",
    "CliRestoreResult",
    "CliValidationResult",
    "CliWritePaths",
    "CommandRunResult",
]
