export const WECHAT_COVER_BASE_HEIGHT = 540
export const WECHAT_HERO_COVER_ASPECT_RATIO = 21 / 9
export const WECHAT_COVER_BASE_WIDTH = Math.round(
	WECHAT_COVER_BASE_HEIGHT * (1 + WECHAT_HERO_COVER_ASPECT_RATIO),
)
