"""
Utility functions for design mode tools.
"""

from .magic_project_design_parser import (
    # Data classes
    MagicProjectConfig,
    CanvasConfig,
    ViewportState,
    BaseElement,
    ImageElement,
    VideoElement,
    TextElement,
    RectangleElement,
    EllipseElement,
    TriangleElement,
    StarElement,
    GroupElement,
    FrameElement,
    CanvasElement,
    ShapeElement,
    InteractionConfig,
    TextStyle,
    RichTextNode,
    RichTextParagraph,
    ParagraphStyle,
    VisualUnderstanding,
    GenerateImageRequest,
    GenerateVideoRequest,
    ValidationResult,
    # Functions
    read_magic_project_js,
    write_magic_project_js,
    write_magic_project_js_v2,
    validate_project_config,
    get_project_file_path,
)
from .magic_project_compression import (
    MAGIC_PROJECT_DESIGN_DATA_PREFIX,
    compress_canvas_data,
    decompress_canvas_data,
    is_compressed_canvas,
)
from .element_details_store import (
    ELEMENT_DETAILS_FILENAME,
    ELEMENT_DETAILS_USER_FILENAME,
    ELEMENT_DETAILS_VERSION,
    HEAVY_FIELDS,
    read_element_details,
    read_readable_element_details,
    read_user_element_details,
    write_element_details,
    extract_element_details,
    strip_heavy_fields,
    merge_element_details,
    merge_readable_element_details,
    prune_orphan_details,
)

__all__ = [
    # Data classes
    "MagicProjectConfig",
    "CanvasConfig",
    "ViewportState",
    "BaseElement",
    "ImageElement",
    "VideoElement",
    "TextElement",
    "RectangleElement",
    "EllipseElement",
    "TriangleElement",
    "StarElement",
    "GroupElement",
    "FrameElement",
    "CanvasElement",
    "ShapeElement",
    "InteractionConfig",
    "TextStyle",
    "RichTextNode",
    "RichTextParagraph",
    "ParagraphStyle",
    "VisualUnderstanding",
    "GenerateImageRequest",
    "GenerateVideoRequest",
    "ValidationResult",
    # Functions
    "read_magic_project_js",
    "write_magic_project_js",
    "write_magic_project_js_v2",
    "validate_project_config",
    "get_project_file_path",
    # Compression
    "MAGIC_PROJECT_DESIGN_DATA_PREFIX",
    "compress_canvas_data",
    "decompress_canvas_data",
    "is_compressed_canvas",
    # Element details store
    "ELEMENT_DETAILS_FILENAME",
    "ELEMENT_DETAILS_USER_FILENAME",
    "ELEMENT_DETAILS_VERSION",
    "HEAVY_FIELDS",
    "read_element_details",
    "read_readable_element_details",
    "read_user_element_details",
    "write_element_details",
    "extract_element_details",
    "strip_heavy_fields",
    "merge_element_details",
    "merge_readable_element_details",
    "prune_orphan_details",
]
