import type { RecordingTopicSection } from "../types/recording-detail"
import { parseRecordingTimeToSeconds } from "./time"

/**
 * Pastel fallback palette aligned with the recording-detail prototype chapter themes.
 * Used only when the topics markdown header omits an explicit `#hex` color token.
 */
const TOPIC_COLORS_FALLBACK = ["#e0e0e0", "#a8d5f7", "#c5e1a5", "#ffd9b3", "#d4c5f0", "#ffccbc"]

/** Normalizes generated topic ids so they are safe as React keys and DOM data attributes. */
function normalizeTopicId(rawId: string, index: number): string {
	return /^[a-zA-Z0-9_-]+$/.test(rawId) ? rawId : `topic_${index + 1}`
}

/** Parses the structured topics markdown generated by the recording summary backend. */
export function parseTopicsMarkdown(markdown: string): RecordingTopicSection[] {
	const titleMatch = markdown.match(/^##\s+.+$/m)
	if (!titleMatch) return []

	const topicsSection = markdown.split(titleMatch[0])[1]
	if (!topicsSection) return []

	return topicsSection
		.split(/\n---\n/)
		.map((block) => block.trim())
		.filter(Boolean)
		.map((block, index) => parseTopicBlock(block, index))
		.filter((topic): topic is RecordingTopicSection => topic != null)
}

/** Parses one topic block into summary copy and clickable related-dialogue items. */
function parseTopicBlock(block: string, index: number): RecordingTopicSection | null {
	// Header format: `### 📌 {id} | {name} | {#hex}` — hex is optional (prototype-aligned).
	const headerMatch = block.match(
		/^### 📌 (\S+)\s*\|\s*([^|\n]+?)(?:\s*\|\s*(#[0-9a-fA-F]{3,8}))?\s*$/m,
	)
	if (!headerMatch) return null

	const [, rawId, rawName, rawColor] = headerMatch
	const h4Lines = block.match(/^####\s+.+$/gm) ?? []
	const summaryTitle = h4Lines[0]?.replace(/^####\s*/, "").trim() ?? ""
	const itemsTitle = h4Lines[1]?.replace(/^####\s*/, "").trim() ?? ""
	const summaryText = extractSectionText(block, h4Lines[0], h4Lines[1])
	const itemsText = extractSectionText(block, h4Lines[1], undefined)
	const speakersMatch = summaryText.match(/^(?:\*\*)?\[(.*?)\](?:\*\*)?\s*\n*/m)
	const summarySpeakers =
		speakersMatch?.[1]
			.split(",")
			.map((speaker) => speaker.trim())
			.filter(Boolean) ?? []
	const cleanSummary = speakersMatch
		? summaryText.replace(/^(?:\*\*)?\[.*?\](?:\*\*)?\s*\n*/m, "").trim()
		: summaryText

	return {
		id: normalizeTopicId(rawId, index),
		name: rawName.trim(),
		color: rawColor?.trim() ?? TOPIC_COLORS_FALLBACK[index % TOPIC_COLORS_FALLBACK.length],
		summaryTitle,
		summaryText: cleanSummary,
		summarySpeakers,
		itemsTitle,
		items: parseTopicItems(itemsText),
	}
}

/** Extracts the text under a markdown heading until the next known heading or the block end. */
function extractSectionText(block: string, startHeading?: string, endHeading?: string): string {
	if (!startHeading) return ""

	const startIndex = block.indexOf(startHeading)
	if (startIndex < 0) return ""

	const contentStart = startIndex + startHeading.length
	const contentEnd = endHeading ? block.indexOf(endHeading, contentStart) : -1
	return (
		contentEnd >= 0 ? block.slice(contentStart, contentEnd) : block.slice(contentStart)
	).trim()
}

/** Parses related-dialogue bullet items from the generated topics markdown. */
function parseTopicItems(markdown: string) {
	const itemRegex =
		/- `(\d{1,3}:\d{2}(?::\d{2})?)(?:-(\d{1,3}:\d{2}(?::\d{2})?))?`\s+(?:\*\*)?(.*?)(?:\*\*)?:\s*(.+)/g
	const items = []
	let match: RegExpExecArray | null

	while ((match = itemRegex.exec(markdown)) !== null) {
		const [, startText, endText, speakersText, text] = match
		items.push({
			time: parseRecordingTimeToSeconds(startText),
			timeEnd: endText ? parseRecordingTimeToSeconds(endText) : undefined,
			speakers: speakersText
				.split(",")
				.map((speaker) => speaker.trim())
				.filter(Boolean),
			text: text.trim(),
		})
	}

	return items
}
