export const RENDER_TIMEOUT_MS = 30000
export const READY_STATE_FALLBACK_MS = 6000
export const READY_STATE_POLL_MS = 50
export const NATIVE_LOAD_WAIT_MS = 1500
export const EXTERNAL_RESOURCE_TIMEOUT_MS = 30000
export const FONTS_READY_TIMEOUT_MS = 8000
